FROM ubuntu

RUN apt-get update

RUN apt-get install -y git

RUN git clone https://github.com/novnc/noVNC

WORKDIR /noVNC

RUN git clone https://github.com/novnc/websockify

RUN apt install -y net-tools python

RUN ln -s $(pwd)/websockify/run /usr/bin/websockify

EXPOSE 8001-8004

EXPOSE 6080

CMD ./utils/launch.sh --listen `expr 8000 + $PLAYER_NUM` --vnc $SERVER:`expr 5900 + $PLAYER_NUM`
